// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApp.Persistence;

#nullable disable

namespace ToDoApp.Persistence.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    [Migration("20230318162746_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoApp.Domain.Entities.ToDoItem", b =>
                {
                    b.Property<int>("ToDoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToDoItemId"));

                    b.Property<bool>("ToDoIsDone")
                        .HasColumnType("bit");

                    b.Property<int?>("ToDoItemId1")
                        .HasColumnType("int");

                    b.Property<string>("ToDoItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToDoItemId");

                    b.HasIndex("ToDoItemId1");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            ToDoItemId = 1,
                            ToDoIsDone = false,
                            ToDoItemName = "MyFirstTodo"
                        },
                        new
                        {
                            ToDoItemId = 2,
                            ToDoIsDone = false,
                            ToDoItemName = "MySecondTodo"
                        },
                        new
                        {
                            ToDoItemId = 3,
                            ToDoIsDone = false,
                            ToDoItemName = "MyThirdTodo"
                        },
                        new
                        {
                            ToDoItemId = 4,
                            ToDoIsDone = false,
                            ToDoItemName = "MyFourthTodo"
                        });
                });

            modelBuilder.Entity("ToDoApp.Domain.Entities.ToDoList", b =>
                {
                    b.Property<int>("ToDoListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToDoListId"));

                    b.Property<int>("ToDoItemId")
                        .HasColumnType("int");

                    b.HasKey("ToDoListId");

                    b.HasIndex("ToDoItemId");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("ToDoApp.Domain.Entities.ToDoItem", b =>
                {
                    b.HasOne("ToDoApp.Domain.Entities.ToDoItem", null)
                        .WithMany("ToDoItems")
                        .HasForeignKey("ToDoItemId1");
                });

            modelBuilder.Entity("ToDoApp.Domain.Entities.ToDoList", b =>
                {
                    b.HasOne("ToDoApp.Domain.Entities.ToDoItem", "ToDoItem")
                        .WithMany()
                        .HasForeignKey("ToDoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDoItem");
                });

            modelBuilder.Entity("ToDoApp.Domain.Entities.ToDoItem", b =>
                {
                    b.Navigation("ToDoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
